project_name: easygen

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    # remove README and LICENSE
    files:
      - none*

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

    # Path to main.go file or main package.
    # Notice: when used with `gomod.proxy`, this must be a package.
    #
    # Default is `.`.
    main: ./cmd/easygen

nfpms:
- maintainer: Tong Sun <suntong@cpan.org>
  description: easygen - Easy to use universal code/text generator
  homepage: https://github.com/go-easygen/easygen
  license: MIT
  formats:
  - deb
  - rpm
  - apk
